//! Runs the built binary against a realistic slicer file and checks the
//! resulting G-code is still coherent.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU32, Ordering};
use std::{env, fs};

use bricklayers::brick;

const BIN: &str = env!("CARGO_BIN_EXE_bricklayers");

/// Three layers of PrusaSlicer-flavoured output: an external perimeter, two
/// internal perimeter loops and some sparse infill, with solid infill top and
/// bottom.
fn sample_gcode() -> String {
    let mut text = String::from(
        "; generated by PrusaSlicer\n\
         M83 ; extruder relative mode\n\
         ; layer_height = 0.2\n",
    );
    for (index, z) in [0.2_f64, 0.4, 0.6, 0.8, 1.0].into_iter().enumerate() {
        text.push_str(";LAYER_CHANGE\n");
        text.push_str(&format!("G1 Z{z:.3} F9000\n"));
        text.push_str(";TYPE:External perimeter\n");
        text.push_str("G1 X0 Y0 F9000\n");
        for (x, y) in [(20.0, 0.0), (20.0, 20.0), (0.0, 20.0), (0.0, 0.0)] {
            text.push_str(&format!("G1 X{x:.3} Y{y:.3} E0.66000\n"));
        }
        text.push_str(";TYPE:Perimeter\n");
        for inset in [0.45_f64, 0.90] {
            text.push_str(&format!("G1 X{inset:.3} Y{inset:.3} F9000\n"));
            let far = 20.0 - inset;
            for (x, y) in [(far, inset), (far, far), (inset, far), (inset, inset)] {
                text.push_str(&format!("G1 X{x:.3} Y{y:.3} E0.64000\n"));
            }
        }
        let solid = index == 0 || index == 4;
        text.push_str(if solid {
            ";TYPE:Solid infill\n"
        } else {
            ";TYPE:Internal infill\n"
        });
        text.push_str("G1 X2 Y2 F9000\n");
        text.push_str("G1 X18 Y18 E1.20000\n");
    }
    text.push_str("M104 S0\n");
    text
}

struct Sandbox(PathBuf);

impl Sandbox {
    fn new(label: &str) -> Self {
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        let id = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = env::temp_dir().join(format!("bricklayers-{label}-{}-{id}", std::process::id()));
        fs::create_dir_all(&path).expect("create sandbox");
        Self(path)
    }

    fn with_gcode(&self, contents: &str) -> PathBuf {
        self.with_bytes(contents.as_bytes())
    }

    fn with_bytes(&self, contents: &[u8]) -> PathBuf {
        let path = self.0.join("part.gcode");
        fs::write(&path, contents).expect("write sample");
        path
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for Sandbox {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn run(args: &[&str]) -> std::process::Output {
    Command::new(BIN).args(args).output().expect("run binary")
}

/// Runs the binary the way a slicer would, with the print configuration
/// exported into the environment.
fn run_with_env(args: &[&str], settings: &[(&str, &str)]) -> std::process::Output {
    Command::new(BIN)
        .args(args)
        .envs(settings.iter().copied())
        .output()
        .expect("run binary")
}

/// Every non-comment line must still look like G-code, and no coordinate may be
/// NaN or infinite.
fn assert_wellformed(gcode: &str) {
    for line in gcode.lines() {
        let body = line.split(';').next().unwrap_or("").trim();
        if body.is_empty() {
            continue;
        }
        assert!(
            body.starts_with(['G', 'M', 'T']),
            "unexpected command: {line}"
        );
        for word in body.split_whitespace().skip(1) {
            let (letter, value) = word.split_at(1);
            if !matches!(letter, "X" | "Y" | "Z" | "E" | "F") {
                continue;
            }
            let parsed: f64 = value.parse().unwrap_or_else(|_| panic!("bad word: {line}"));
            assert!(parsed.is_finite(), "non-finite value: {line}");
        }
    }
}

#[test]
fn brick_rewrites_the_file_in_place() {
    let sandbox = Sandbox::new("brick-inplace");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);

    let output = run(&["brick", path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert_ne!(result, source, "file should have been modified");
    assert_wellformed(&result);
    assert!(result.contains("bricklayers brick raised"));
    assert!(result.contains("bricklayers brick reset"));
}

#[test]
fn brick_leaves_external_perimeters_and_infill_untouched() {
    let sandbox = Sandbox::new("brick-untouched");
    let path = sandbox.with_gcode(&sample_gcode());
    run(&["brick", path.to_str().unwrap()]);

    let result = fs::read_to_string(&path).expect("read result");
    assert_eq!(
        result.matches("E0.66000").count(),
        20,
        "external perimeter extrusions must be unchanged"
    );
    assert_eq!(
        result.matches("E1.20000").count(),
        5,
        "infill extrusions must be unchanged"
    );
}

#[test]
fn brick_never_leaves_the_nozzle_raised_into_the_next_region() {
    let sandbox = Sandbox::new("brick-z");
    let path = sandbox.with_gcode(&sample_gcode());
    run(&["brick", path.to_str().unwrap()]);
    let result = fs::read_to_string(&path).expect("read result");

    let mut z = 0.0_f64;
    let mut layer_z = 0.0_f64;
    for line in result.lines() {
        if let Some(rest) = line.strip_prefix("G1 Z") {
            z = rest
                .split_whitespace()
                .next()
                .and_then(|value| value.parse().ok())
                .expect("Z value");
            if !line.contains("bricklayers") {
                layer_z = z;
            }
        }
        if line.starts_with(";TYPE:") && !line.contains("Perimeter") {
            assert_eq!(z, layer_z, "entered {line} while raised");
        }
    }
}

#[test]
fn a_second_run_of_the_same_transform_is_refused() {
    let sandbox = Sandbox::new("rerun");
    let path = sandbox.with_gcode(&sample_gcode());
    let file = path.to_str().unwrap();

    assert!(run(&["brick", file]).status.success());
    let once = fs::read_to_string(&path).expect("read result");

    let output = run(&["brick", file]);
    assert!(!output.status.success(), "a repeat run must fail");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("already carries brick marks"), "{report}");
    assert_eq!(
        fs::read_to_string(&path).unwrap(),
        once,
        "a refused run must leave the file alone"
    );

    let output = run(&["brick", "--force", file]);
    assert!(output.status.success(), "--force overrides: {output:?}");
    assert_ne!(fs::read_to_string(&path).unwrap(), once);
}

/// The wave transform was removed. A slicer still configured to call it has to
/// be told, rather than have its file handed back silently unprocessed.
#[test]
fn the_wave_transform_is_gone() {
    let sandbox = Sandbox::new("no-wave");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);
    let file = path.to_str().unwrap();

    for args in [vec!["wave", file], vec!["wave", "--amplitude", "0.3", file]] {
        let output = run(&args);
        assert!(!output.status.success(), "{args:?} was accepted");
        assert_eq!(
            fs::read_to_string(&path).unwrap(),
            source,
            "{args:?} touched the file"
        );
    }

    let output = run(&["--help"]);
    let help = String::from_utf8_lossy(&output.stdout);
    assert!(!help.contains("wave"), "{help}");
}

#[test]
fn output_flag_leaves_the_input_alone() {
    let sandbox = Sandbox::new("output-flag");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);
    let target = sandbox.path().join("out.gcode");

    let output = run(&[
        "brick",
        "-o",
        target.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");
    assert_eq!(fs::read_to_string(&path).unwrap(), source);
    assert!(fs::read_to_string(&target).unwrap().contains("bricklayers"));
}

#[test]
fn no_temporary_files_are_left_behind() {
    let sandbox = Sandbox::new("atomic");
    let path = sandbox.with_gcode(&sample_gcode());
    run(&["brick", path.to_str().unwrap()]);

    let leftovers: Vec<_> = fs::read_dir(sandbox.path())
        .unwrap()
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name())
        .filter(|name| name != "part.gcode")
        .collect();
    assert!(leftovers.is_empty(), "left behind {leftovers:?}");
}

#[test]
fn a_missing_file_fails_with_a_readable_message() {
    let output = run(&["brick", "/nonexistent/part.gcode"]);
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("/nonexistent/part.gcode"), "{stderr}");
}

/// A rewrite is a fresh file renamed over the original, so it starts from the
/// process umask rather than from the permissions the user chose.
#[cfg(unix)]
#[test]
fn a_rewrite_keeps_the_permissions_the_file_had() {
    use std::os::unix::fs::PermissionsExt;

    let sandbox = Sandbox::new("mode");
    let path = sandbox.with_gcode(&sample_gcode());
    fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).expect("chmod");

    let output = run(&["brick", path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let mode = |path: &Path| fs::metadata(path).expect("stat").permissions().mode() & 0o777;
    assert_eq!(mode(&path), 0o600, "an in-place rewrite widened the file");

    // A new destination has no permissions of its own, so it takes the input's
    // rather than leaving a private file's contents world readable.
    let target = sandbox.path().join("copy.gcode");
    let output = run(&[
        "brick",
        "--force",
        "-o",
        target.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");
    assert_eq!(mode(&target), 0o600, "a copy widened the file");
}

#[test]
fn the_slicer_environment_supplies_the_first_layer_height() {
    let sandbox = Sandbox::new("env-first-layer");
    let path = sandbox.with_gcode(&sample_gcode());
    let file = path.to_str().unwrap();

    // A 0.3 mm first layer under 0.2 mm layers: raised, its bead spans that
    // plus the 0.1 shift, so it needs 4/3 of the flow rather than 3/2.
    let output = run_with_env(
        &["brick", file],
        &[
            ("SLIC3R_LAYER_HEIGHT", "0.2"),
            ("SLIC3R_FIRST_LAYER_HEIGHT", "0.3"),
        ],
    );
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert_wellformed(&result);
    assert!(result.contains("E0.85333"), "0.64 x 4/3 missing");
    assert!(
        !result.contains("E0.96000"),
        "0.64 x 3/2 assumes both heights are equal"
    );
}

#[test]
fn a_comment_that_is_not_utf8_does_not_stop_the_transform() {
    let sandbox = Sandbox::new("latin1");
    // Slicers copy object names into comments in the host's encoding, so a file
    // of otherwise plain ASCII G-code can carry a stray byte.
    let mut source = sample_gcode().into_bytes();
    let mut named = b"; printing object Caf\xe9\n".to_vec();
    named.append(&mut source);
    let path = sandbox.with_bytes(&named);

    let output = run(&["brick", path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("result is valid UTF-8");
    assert_wellformed(&result);
    assert!(result.contains("bricklayers brick raised"), "{result}");
    assert!(result.contains("; printing object Caf"), "{result}");
    assert_eq!(
        result.matches("E0.66000").count(),
        20,
        "external perimeter extrusions must still be untouched"
    );
}

#[test]
fn verbose_reports_a_summary() {
    let sandbox = Sandbox::new("verbose");
    let path = sandbox.with_gcode(&sample_gcode());
    let output = run(&[
        "brick",
        "--extrusion-multiplier",
        "1.05",
        "--verbose",
        path.to_str().unwrap(),
    ]);

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("5 layers"), "{stderr}");
    assert!(stderr.contains("10 internal loops"), "{stderr}");
    // One per layer, less the top one, which caps the wall flat.
    assert!(stderr.contains("4 raised"), "{stderr}");
    assert!(stderr.contains("in raised loops"), "{stderr}");
    assert!(
        stderr.contains("--extrusion-multiplier 1.05"),
        "the default multiplier must be priced in the summary: {stderr}"
    );
}

#[test]
fn help_and_version_are_available() {
    for command in [["--help"], ["--version"]] {
        let output = run(&command);
        assert!(output.status.success(), "{command:?} failed");
        assert!(!output.stdout.is_empty());
    }
    assert!(run(&["brick", "--help"]).status.success());
}

#[test]
fn the_slicer_environment_supplies_the_layer_height() {
    let sandbox = Sandbox::new("env-layer-height");
    // Without the comment the Z steps would measure 0.2, so 0.3 can only have
    // come from the environment.
    let path = sandbox.with_gcode(&sample_gcode().replace("; layer_height = 0.2\n", ""));
    let file = path.to_str().unwrap();

    let output = run_with_env(
        &["brick", "--verbose", file],
        &[("SLIC3R_LAYER_HEIGHT", "0.3")],
    );
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("raised by 0.150 mm"), "{report}");
    assert!(!report.contains("warning"), "{report}");

    // Back to a pristine file: the first run left its marks, and a second
    // brick over those is refused.
    sandbox.with_gcode(&sample_gcode().replace("; layer_height = 0.2\n", ""));
    let output = run_with_env(
        &["brick", "--verbose", "--layer-height", "0.1", file],
        &[("SLIC3R_LAYER_HEIGHT", "0.3")],
    );
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(
        report.contains("raised by 0.050 mm"),
        "the flag must win: {report}"
    );
}

#[test]
fn slicer_settings_that_defeat_the_transform_are_reported() {
    let sandbox = Sandbox::new("env-warnings");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(
        &["brick", path.to_str().unwrap()],
        &[
            ("SLIC3R_WALL_SEQUENCE", "inner wall/outer wall"),
            ("SLIC3R_WALL_LOOPS", "1"),
            ("SLIC3R_SPIRAL_MODE", "1"),
            ("SLIC3R_ENABLE_ARC_FITTING", "1"),
        ],
    );
    assert!(output.status.success(), "{output:?}");

    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("spiral vase"), "{report}");
    assert!(report.contains("arc fitting"), "{report}");
    assert!(report.contains("1 wall(s)"), "{report}");
}

/// Two walls leave exactly one internal perimeter per region. That loop is
/// raised against the external perimeter it was inset from, so the run bricks
/// rather than reporting the file as beyond help.
#[test]
fn two_walls_are_bricked_rather_than_refused() {
    let sandbox = Sandbox::new("env-two-walls");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(
        &["brick", "--verbose", path.to_str().unwrap()],
        &[("SLIC3R_PERIMETERS", "2")],
    );
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(!report.contains("wall(s)"), "{report}");
    assert!(report.contains("4 raised"), "{report}");
}

/// One wall is the visible one, with nothing hidden behind it to shift, so the
/// run has to say so rather than report having done nothing.
#[test]
fn a_single_wall_is_reported_as_leaving_nothing_to_raise() {
    let sandbox = Sandbox::new("env-one-wall");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(
        &["brick", path.to_str().unwrap()],
        &[("SLIC3R_PERIMETERS", "1")],
    );
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("1 wall(s)"), "{report}");
    assert!(report.contains("two walls or more"), "{report}");
}

/// Arc fitting is a print setting, so the file carries the evidence even when
/// the tool is run by hand rather than by a slicer. `brick` shifts an arc with
/// the loop around it, so it has nothing to say about one.
#[test]
fn walls_emitted_as_arcs_draw_no_warning() {
    let sandbox = Sandbox::new("arcs");
    let arced = sample_gcode().replace(
        "G1 X19.550 Y19.550 E0.64000",
        "G3 X19.550 Y19.550 I1 J1 E0.64000",
    );
    let path = sandbox.with_gcode(&arced);

    let output = run(&["brick", path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(!report.contains("arc"), "{report}");
}

#[test]
fn a_well_configured_slicer_draws_no_warnings() {
    let sandbox = Sandbox::new("env-quiet");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(
        &["brick", path.to_str().unwrap()],
        &[
            ("SLIC3R_EXTERNAL_PERIMETERS_FIRST", "1"),
            ("SLIC3R_PERIMETERS", "3"),
            ("SLIC3R_SPIRAL_VASE", "0"),
            ("SLIC3R_ARC_FITTING", "disabled"),
        ],
    );
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(!report.contains("warning"), "{report}");
}

/// The slicer setting is only a claim, and detection reads prose to interpret
/// it. `--wall-order` has to beat that claim in both directions — the flag it
/// replaced could only turn external-first on, so a file misread as
/// external-first had no way back.
#[test]
fn the_wall_order_flag_overrides_what_the_slicer_says() {
    let sandbox = Sandbox::new("wall-order");
    let claims_external_first = [("SLIC3R_EXTERNAL_PERIMETERS_FIRST", "1")];

    let bricked = |flag: Option<&str>| {
        let path = sandbox.with_gcode(&sample_gcode());
        let mut args = vec!["brick"];
        if let Some(flag) = flag {
            args.extend(["--wall-order", flag]);
        }
        args.push(path.to_str().unwrap());
        let output = run_with_env(&args, &claims_external_first);
        assert!(output.status.success(), "{output:?}");
        let result = fs::read_to_string(&path).expect("read result");
        assert_wellformed(&result);
        result
    };

    let detected = bricked(None);
    assert_eq!(detected, bricked(Some("auto")), "auto is not the default");
    assert_eq!(
        detected,
        bricked(Some("external-first")),
        "forcing what was detected changed the output"
    );
    assert_ne!(
        detected,
        bricked(Some("internal-first")),
        "internal-first did not override the slicer's setting"
    );
}

#[test]
fn crlf_input_is_accepted() {
    let sandbox = Sandbox::new("crlf");
    let path = sandbox.with_gcode(&sample_gcode().replace('\n', "\r\n"));
    let output = run(&["brick", path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert!(!result.contains('\r'));
    assert_wellformed(&result);
}

/// The binary streams a file through the same transform the library runs over a
/// string, so the two have to agree byte for byte. This is what pins the line
/// reader, the buffered writer and the atomic rename to the reference result.
#[test]
fn streaming_a_file_matches_rewriting_it_in_memory() {
    let sandbox = Sandbox::new("streaming-matches");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);

    let in_memory = brick::apply(&source, &brick::Config::default()).gcode;
    let out = sandbox.path().join("brick.gcode");
    let output = run(&[
        "brick",
        "--output",
        out.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");

    let streamed = fs::read_to_string(&out).expect("read result");
    assert_eq!(streamed, in_memory, "brick diverged from the library");
}

/// Nothing this tool writes may ask the nozzle to go below the build plate.
#[test]
fn no_transform_ever_commands_a_z_below_the_bed() {
    let sandbox = Sandbox::new("below-bed");
    let path = sandbox.with_gcode(&sample_gcode());

    for args in [
        vec!["brick"],
        vec!["brick", "--extrusion-multiplier", "1.05"],
        vec!["brick", "--reorder-loops"],
    ] {
        let out = sandbox.path().join(format!("{}.gcode", args.join("-")));
        let mut call = args.clone();
        call.extend(["--output", out.to_str().unwrap(), path.to_str().unwrap()]);
        let output = run(&call);
        assert!(output.status.success(), "{args:?}: {output:?}");

        let result = fs::read_to_string(&out).expect("read result");
        assert_wellformed(&result);
        for line in result.lines() {
            let body = line.split(';').next().unwrap_or("");
            for word in body.split_whitespace().skip(1) {
                if let Some(digits) = word.strip_prefix('Z') {
                    let z: f64 = digits.parse().expect("a number");
                    assert!(z >= 0.0, "{args:?} commanded {line}");
                }
            }
        }
    }
}

/// Numbers are written digit by digit rather than through the standard
/// formatter. A coordinate that sits exactly on a rounding boundary is where
/// the two could part, so the whole binary is checked against a file made of
/// them: every value must read back as the one the formatter would print.
#[test]
fn coordinates_on_a_rounding_boundary_survive_the_binary() {
    let sandbox = Sandbox::new("rounding");

    let mut source = String::from("; layer_height = 0.2\nM83\n");
    for layer in 0..4 {
        let z = 0.2 + f64::from(layer) * 0.2;
        source.push_str(";LAYER_CHANGE\n");
        source.push_str(&format!("G1 Z{z:.3} F600\n"));
        source.push_str(";TYPE:Perimeter\n");
        for inset in [0.0_f64, 0.4375] {
            // Odd sixteenths land exactly on a half-way point at three
            // decimals, where rounding goes to even rather than away from zero.
            let (near, far) = (1.0625 + inset, 9.9375 - inset);
            source.push_str(&format!("G1 X{near} Y{near} F9000\n"));
            for (x, y) in [(far, near), (far, far), (near, far), (near, near)] {
                source.push_str(&format!("G1 X{x} Y{y} E0.53125\n"));
            }
        }
    }
    let path = sandbox.with_gcode(&source);

    let out = sandbox.path().join("brick.gcode");
    let output = run(&[
        "brick",
        "--output",
        out.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&out).expect("read result");
    assert_wellformed(&result);
    for line in result.lines() {
        let body = line.split(';').next().unwrap_or("");
        for word in body.split_whitespace().skip(1) {
            let (letter, digits) = word.split_at(1);
            if !matches!(letter, "X" | "Y" | "Z" | "E" | "F") {
                continue;
            }
            let value: f64 = digits.parse().expect("a number");
            let decimals = digits.split_once('.').map_or(0, |(_, tail)| tail.len());
            assert_eq!(
                digits,
                format!("{value:.decimals$}"),
                "wrote {word} in: {line}"
            );
        }
    }
}
