//! Runs the built binary against a realistic slicer file and checks the
//! resulting G-code is still coherent.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU32, Ordering};
use std::{env, fs};

use bricklayers::brick;

const BIN: &str = env!("CARGO_BIN_EXE_bricklayers");

/// Three layers of PrusaSlicer-flavoured output: an external perimeter, two
/// internal perimeter loops and some sparse infill, with solid infill top and
/// bottom.
fn sample_gcode() -> String {
    gcode_at(&[0.2, 0.4, 0.6, 0.8, 1.0])
}

/// [`sample_gcode`] sliced so that each layer tops out at the given plane, so
/// a file whose slicer varied the height can be driven through the binary.
fn gcode_at(planes: &[f64]) -> String {
    let mut text = String::from(
        "; generated by PrusaSlicer\n\
         M83 ; extruder relative mode\n\
         ; layer_height = 0.2\n",
    );
    for (index, z) in planes.iter().copied().enumerate() {
        text.push_str(";LAYER_CHANGE\n");
        text.push_str(&format!("G1 Z{z:.3} F9000\n"));
        text.push_str(";TYPE:External perimeter\n");
        text.push_str("G1 X0 Y0 F9000\n");
        for (x, y) in [(20.0, 0.0), (20.0, 20.0), (0.0, 20.0), (0.0, 0.0)] {
            text.push_str(&format!("G1 X{x:.3} Y{y:.3} E0.66000\n"));
        }
        text.push_str(";TYPE:Perimeter\n");
        for inset in [0.45_f64, 0.90] {
            text.push_str(&format!("G1 X{inset:.3} Y{inset:.3} F9000\n"));
            let far = 20.0 - inset;
            for (x, y) in [(far, inset), (far, far), (inset, far), (inset, inset)] {
                text.push_str(&format!("G1 X{x:.3} Y{y:.3} E0.64000\n"));
            }
        }
        let solid = index == 0 || index + 1 == planes.len();
        text.push_str(if solid {
            ";TYPE:Solid infill\n"
        } else {
            ";TYPE:Internal infill\n"
        });
        text.push_str("G1 X2 Y2 F9000\n");
        text.push_str("G1 X18 Y18 E1.20000\n");
    }
    text.push_str("M104 S0\n");
    text
}

struct Sandbox(PathBuf);

impl Sandbox {
    fn new(label: &str) -> Self {
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        let id = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = env::temp_dir().join(format!("bricklayers-{label}-{}-{id}", std::process::id()));
        fs::create_dir_all(&path).expect("create sandbox");
        Self(path)
    }

    fn with_gcode(&self, contents: &str) -> PathBuf {
        self.with_bytes(contents.as_bytes())
    }

    fn with_bytes(&self, contents: &[u8]) -> PathBuf {
        let path = self.0.join("part.gcode");
        fs::write(&path, contents).expect("write sample");
        path
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for Sandbox {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn run(args: &[&str]) -> std::process::Output {
    Command::new(BIN).args(args).output().expect("run binary")
}

/// Runs the binary the way a slicer would, with the print configuration
/// exported into the environment.
fn run_with_env(args: &[&str], settings: &[(&str, &str)]) -> std::process::Output {
    Command::new(BIN)
        .args(args)
        .envs(settings.iter().copied())
        .output()
        .expect("run binary")
}

/// Every non-comment line must still look like G-code, and no coordinate may be
/// NaN or infinite.
fn assert_wellformed(gcode: &str) {
    for line in gcode.lines() {
        let body = line.split(';').next().unwrap_or("").trim();
        if body.is_empty() {
            continue;
        }
        assert!(
            body.starts_with(['G', 'M', 'T']),
            "unexpected command: {line}"
        );
        for word in body.split_whitespace().skip(1) {
            let (letter, value) = word.split_at(1);
            if !matches!(letter, "X" | "Y" | "Z" | "E" | "F") {
                continue;
            }
            let parsed: f64 = value.parse().unwrap_or_else(|_| panic!("bad word: {line}"));
            assert!(parsed.is_finite(), "non-finite value: {line}");
        }
    }
}

#[test]
fn brick_rewrites_the_file_in_place() {
    let sandbox = Sandbox::new("brick-inplace");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);

    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert_ne!(result, source, "file should have been modified");
    assert_wellformed(&result);
    assert!(result.contains("bricklayers brick raised"));
    assert!(result.contains("bricklayers brick reset"));
}

#[test]
fn brick_leaves_infill_untouched_and_meters_every_wall() {
    let sandbox = Sandbox::new("brick-untouched");
    let path = sandbox.with_gcode(&sample_gcode());
    run(&[path.to_str().unwrap()]);

    let result = fs::read_to_string(&path).expect("read result");
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "only the bed layer's visible wall may be left as sliced"
    );
    assert_eq!(
        result.matches("E1.20000").count(),
        5,
        "infill extrusions must be unchanged"
    );
}

#[test]
fn brick_never_leaves_the_nozzle_raised_into_the_next_region() {
    let sandbox = Sandbox::new("brick-z");
    let path = sandbox.with_gcode(&sample_gcode());
    run(&[path.to_str().unwrap()]);
    let result = fs::read_to_string(&path).expect("read result");

    let mut z = 0.0_f64;
    let mut layer_z = 0.0_f64;
    for line in result.lines() {
        if let Some(rest) = line.strip_prefix("G1 Z") {
            z = rest
                .split_whitespace()
                .next()
                .and_then(|value| value.parse().ok())
                .expect("Z value");
            if !line.contains("bricklayers") {
                layer_z = z;
            }
        }
        if line.starts_with(";TYPE:") && !line.contains("Perimeter") {
            assert_eq!(z, layer_z, "entered {line} while raised");
        }
    }
}

#[test]
fn a_second_run_over_the_same_file_is_refused() {
    let sandbox = Sandbox::new("rerun");
    let path = sandbox.with_gcode(&sample_gcode());
    let file = path.to_str().unwrap();

    assert!(run(&[file]).status.success());
    let once = fs::read_to_string(&path).expect("read result");

    let output = run(&[file]);
    assert!(!output.status.success(), "a repeat run must fail");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("has already been bricked"), "{report}");
    assert_eq!(
        fs::read_to_string(&path).unwrap(),
        once,
        "a refused run must leave the file alone"
    );

    let output = run(&["--force", file]);
    assert!(output.status.success(), "--force overrides: {output:?}");
    assert_ne!(fs::read_to_string(&path).unwrap(), once);
}

/// The wave transform was removed. A slicer still configured to call it has to
/// be told, rather than have its file handed back silently unprocessed.
#[test]
fn the_wave_transform_is_gone() {
    let sandbox = Sandbox::new("no-wave");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);
    let file = path.to_str().unwrap();

    for args in [vec!["wave", file], vec!["wave", "--amplitude", "0.3", file]] {
        let output = run(&args);
        assert!(!output.status.success(), "{args:?} was accepted");
        assert_eq!(
            fs::read_to_string(&path).unwrap(),
            source,
            "{args:?} touched the file"
        );
    }

    let output = run(&["--help"]);
    let help = String::from_utf8_lossy(&output.stdout);
    assert!(!help.contains("wave"), "{help}");
}

/// The version comes from the tag the release workflow stamped in, so a build
/// nobody released says "dev" rather than a number kept in the source.
#[test]
fn the_version_comes_from_the_release_tag() {
    let expected = option_env!("BRICKLAYERS_VERSION").unwrap_or("dev");
    let output = run(&["--version"]);
    assert!(output.status.success(), "{output:?}");
    assert_eq!(
        String::from_utf8_lossy(&output.stdout).trim(),
        format!("bricklayers {expected}")
    );
}

#[test]
fn output_flag_leaves_the_input_alone() {
    let sandbox = Sandbox::new("output-flag");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);
    let target = sandbox.path().join("out.gcode");

    let output = run(&["-o", target.to_str().unwrap(), path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");
    assert_eq!(fs::read_to_string(&path).unwrap(), source);
    assert!(fs::read_to_string(&target).unwrap().contains("bricklayers"));
}

#[test]
fn no_temporary_files_are_left_behind() {
    let sandbox = Sandbox::new("atomic");
    let path = sandbox.with_gcode(&sample_gcode());
    run(&[path.to_str().unwrap()]);

    let leftovers: Vec<_> = fs::read_dir(sandbox.path())
        .unwrap()
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name())
        .filter(|name| name != "part.gcode")
        .collect();
    assert!(leftovers.is_empty(), "left behind {leftovers:?}");
}

#[test]
fn a_missing_file_fails_with_a_readable_message() {
    let output = run(&["/nonexistent/part.gcode"]);
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("/nonexistent/part.gcode"), "{stderr}");
}

/// A rewrite is a fresh file renamed over the original, so it starts from the
/// process umask rather than from the permissions the user chose.
#[cfg(unix)]
#[test]
fn a_rewrite_keeps_the_permissions_the_file_had() {
    use std::os::unix::fs::PermissionsExt;

    let sandbox = Sandbox::new("mode");
    let path = sandbox.with_gcode(&sample_gcode());
    fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).expect("chmod");

    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let mode = |path: &Path| fs::metadata(path).expect("stat").permissions().mode() & 0o777;
    assert_eq!(mode(&path), 0o600, "an in-place rewrite widened the file");

    // A new destination has no permissions of its own, so it takes the input's
    // rather than leaving a private file's contents world readable.
    let target = sandbox.path().join("copy.gcode");
    let output = run(&[
        "--force",
        "-o",
        target.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");
    assert_eq!(mode(&target), 0o600, "a copy widened the file");
}

/// A bead laid on the build plate is pressed against the plate rather than
/// against a layer, so raising it presses nothing and the extra flow it would
/// need spreads sideways. There is no seam under it to stagger either. On a
/// Benchy this filled in the bottom nameplate, which is one layer deep.
#[test]
fn the_layer_laid_on_the_bed_is_left_exactly_as_sliced() {
    let sandbox = Sandbox::new("bed-layer");
    let path = sandbox.with_gcode(&sample_gcode());
    let file = path.to_str().unwrap();

    let output = run_with_env(
        &[file],
        &[
            ("SLIC3R_LAYER_HEIGHT", "0.2"),
            ("SLIC3R_FIRST_LAYER_HEIGHT", "0.3"),
        ],
    );
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert_wellformed(&result);
    let bed: String = result
        .lines()
        .take_while(|line| !line.contains("Z0.4"))
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        !bed.contains("bricklayers"),
        "the bed layer must come through untouched:\n{bed}"
    );
}

#[test]
fn a_comment_that_is_not_utf8_does_not_stop_the_transform() {
    let sandbox = Sandbox::new("latin1");
    // Slicers copy object names into comments in the host's encoding, so a file
    // of otherwise plain ASCII G-code can carry a stray byte.
    let mut source = sample_gcode().into_bytes();
    let mut named = b"; printing object Caf\xe9\n".to_vec();
    named.append(&mut source);
    let path = sandbox.with_bytes(&named);

    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("result is valid UTF-8");
    assert_wellformed(&result);
    assert!(result.contains("bricklayers brick raised"), "{result}");
    assert!(result.contains("; printing object Caf"), "{result}");
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "only the bed layer's visible wall may be left as sliced"
    );
}

#[test]
fn a_wall_closed_by_a_solid_surface_partway_up_is_left_flat() {
    // A shoulder. The right-hand column of wall stops at the third layer and
    // a solid surface is printed over it at the fourth, while the left-hand
    // one carries on to the top. A bead left raised under that surface takes
    // half the gap the slicer metered a whole layer of material for.
    let mut text = String::from(
        "; generated by PrusaSlicer\n\
         M83 ; extruder relative mode\n\
         ; layer_height = 0.2\n",
    );
    for (index, z) in [0.2, 0.4, 0.6, 0.8, 1.0].iter().enumerate() {
        text.push_str(&format!(
            ";LAYER_CHANGE\nG1 Z{z:.3} F9000\n;TYPE:Perimeter\n"
        ));
        let shoulder = index < 3;
        for origin in if shoulder {
            &[0.0, 40.0][..]
        } else {
            &[0.0][..]
        } {
            for inset in [0.45_f64, 0.90] {
                let (near, far) = (origin + inset, origin + 20.0 - inset);
                text.push_str(&format!("G1 X{near:.3} Y{near:.3} F9000\n"));
                for (x, y) in [(far, near), (far, far), (near, far), (near, near)] {
                    text.push_str(&format!("G1 X{x:.3} Y{y:.3} E0.64000\n"));
                }
            }
        }
        if !shoulder {
            text.push_str(";TYPE:Solid infill\nG1 X42 Y42 F9000\nG1 X58 Y58 E1.20000\n");
        }
    }
    text.push_str("M104 S0\n");

    let sandbox = Sandbox::new("shoulder");
    let path = sandbox.with_gcode(&text);
    let output = run(&["--verbose", path.to_str().unwrap()]);
    assert!(output.status.success());
    let out = std::fs::read_to_string(&path).unwrap();
    assert_wellformed(&out);

    // Every raise is undone before the nozzle leaves the loop it belongs to,
    // so the shoulder's own stretch of each layer can be read on its own. The
    // travel to X40.450 is the one that reaches it.
    let layers: Vec<&str> = out.split(";LAYER_CHANGE").collect();
    let shoulder_of = |layer: usize| {
        layers[layer]
            .split_once("X40.450 Y40.450 F9000")
            .expect("the travel that reaches the shoulder")
            .1
    };
    assert!(
        !shoulder_of(3).contains("bricklayers brick raised"),
        "the wall that stops must finish on the plane: {}",
        shoulder_of(3)
    );
    assert!(
        shoulder_of(2).contains("bricklayers brick raised"),
        "while the layer below it still bricks: {}",
        shoulder_of(2)
    );
    assert!(
        layers[3].contains("bricklayers brick raised"),
        "and so does the wall that carries on, on the same layer: {}",
        layers[3]
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("left flat where the wall ends"), "{stderr}");
}

#[test]
fn verbose_reports_a_summary() {
    let sandbox = Sandbox::new("verbose");
    let path = sandbox.with_gcode(&format!(
        "; inner_wall_line_width = 0.45\n{}",
        sample_gcode()
    ));
    let output = run(&["--verbose", path.to_str().unwrap()]);

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("5 layers"), "{stderr}");
    // Three walls a layer, the visible one included.
    assert!(stderr.contains("15 internal loops"), "{stderr}");
    // One per layer, less the bed layer, which is never raised, and the top
    // one, which caps the wall flat.
    assert!(stderr.contains("3 raised"), "{stderr}");
    assert!(stderr.contains("in raised loops"), "{stderr}");
    assert!(
        stderr.contains("a flow of 1.025"),
        "the flow that was applied must be priced in the summary: {stderr}"
    );
}

/// A file that never states how wide its walls were metered still gets a flow,
/// but it is the shipped default rather than this print's own geometry, and
/// the difference has to be visible or "read off the file" is a claim the user
/// cannot check.
#[test]
fn a_file_that_states_no_width_says_the_flow_is_a_default() {
    let sandbox = Sandbox::new("no-width");
    let path = sandbox.with_gcode(&sample_gcode());
    let output = run(&["--verbose", path.to_str().unwrap()]);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("states no internal wall width"), "{stderr}");

    let stated = Sandbox::new("width");
    let path = stated.with_gcode(&format!(
        "; inner_wall_line_width = 0.45\n{}",
        sample_gcode()
    ));
    let output = run(&["--verbose", path.to_str().unwrap()]);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        !stderr.contains("states no internal wall width"),
        "{stderr}"
    );
}

/// Nothing has to be passed for the walls to be metered: the flow comes off
/// the geometry the file states about itself, so a profile laying narrow beads
/// through a fine nozzle pays more than one laying wide ones.
#[test]
fn the_flow_is_read_off_the_file_with_no_flag_given() {
    let report = |stated: &str| {
        let sandbox = Sandbox::new("derived-flow");
        let path = sandbox.with_gcode(&format!(
            "; nozzle_diameter = 0.4\n; inner_wall_line_width = {stated}\n{}",
            sample_gcode()
        ));
        let output = run(&["--verbose", path.to_str().unwrap()]);
        String::from_utf8_lossy(&output.stderr).into_owned()
    };
    let narrow = report("0.35");
    assert!(narrow.contains("a flow of 1.033"), "{narrow}");
    let wide = report("0.65");
    assert!(wide.contains("a flow of 1.017"), "{wide}");
    // A percentage is of the nozzle, and 0.4 mm of it is the reference wall.
    let share = report("112.5%");
    assert!(share.contains("a flow of 1.025"), "{share}");
}

/// The dial names the extra a wall takes where the layer is as thick as the
/// nozzle, so a 0.2 mm layer through a 0.4 mm nozzle takes half of it. The
/// visible wall moves with it so the part keeps its dimensions either way.
#[test]
fn the_extra_flow_dial_sets_the_slope_the_geometry_follows() {
    let report = |percent: &str| {
        let sandbox = Sandbox::new("extra-flow");
        let path = sandbox.with_gcode(&format!(
            "; inner_wall_line_width = 0.45\n{}",
            sample_gcode()
        ));
        let output = run(&["--extra-flow", percent, "--verbose", path.to_str().unwrap()]);
        assert!(output.status.success(), "{output:?}");
        String::from_utf8_lossy(&output.stderr).into_owned()
    };
    let half = report("2.5");
    assert!(half.contains("a flow of 1.012"), "{half}");
    assert!(half.contains("--extra-flow 2.5%"), "{half}");

    let more = report("10");
    assert!(more.contains("a flow of 1.050"), "{more}");

    let none = report("0");
    assert!(none.contains("a flow of 1.000"), "{none}");

    // Left alone it is not named, because there is nothing to explain.
    let sandbox = Sandbox::new("extra-flow-default");
    let path = sandbox.with_gcode(&format!(
        "; inner_wall_line_width = 0.45\n{}",
        sample_gcode()
    ));
    let output = run(&["--verbose", path.to_str().unwrap()]);
    let plain = String::from_utf8_lossy(&output.stderr);
    assert!(plain.contains("a flow of 1.025"), "{plain}");
    assert!(!plain.contains("--extra-flow"), "{plain}");
}

/// A slicer running this as a post-processing script exports its whole
/// configuration, and what it says outranks the copy in the file.
#[test]
fn the_slicer_environment_states_the_width_too() {
    let sandbox = Sandbox::new("env-width");
    let path = sandbox.with_gcode(&format!(
        "; inner_wall_line_width = 0.45\n{}",
        sample_gcode()
    ));
    let output = run_with_env(
        &["--verbose", path.to_str().unwrap()],
        &[
            ("SLIC3R_NOZZLE_DIAMETER", "0.4"),
            ("SLIC3R_PERIMETER_EXTRUSION_WIDTH", "87.5%"),
        ],
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("a flow of 1.033"), "{stderr}");
}

/// The stagger is half a layer, so the step it leaves grows with the layer
/// height while the nozzle that has to clear it does not. Nothing here can fix
/// that without giving up the stagger, so it is said plainly instead.
#[test]
fn a_layer_more_than_half_the_nozzle_is_warned_about() {
    let sandbox = Sandbox::new("thick-layer");
    let path = sandbox.with_gcode(&format!(
        "; nozzle_diameter = 0.4\n; layer_height = 0.3\n{}",
        gcode_at(&[0.3, 0.6, 0.9, 1.2, 1.5])
    ));
    let output = run(&[path.to_str().unwrap()]);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("warning"), "{stderr}");
    assert!(stderr.contains("0.4 mm nozzle"), "{stderr}");

    // The same file at a layer the nozzle can clear says nothing.
    let quiet = Sandbox::new("thin-layer");
    let path = quiet.with_gcode(&format!("; nozzle_diameter = 0.4\n{}", sample_gcode()));
    let output = run(&[path.to_str().unwrap()]);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(!stderr.contains("warning"), "{stderr}");
}

/// The flow is for the walls, the visible one included: every wall above the
/// bed is re-metered, and nothing that is not a wall — the solid surfaces that
/// close the part top and bottom, the infill between them — is touched.
#[test]
fn every_wall_above_the_bed_is_rescaled_and_nothing_else_is() {
    let sandbox = Sandbox::new("walls");
    let path = sandbox.with_gcode(&sample_gcode());
    let output = run(&["--verbose", path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert_wellformed(&result);
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "only the bed layer's visible wall may be left as sliced"
    );
    assert_eq!(
        result.matches("E1.20000").count(),
        5,
        "infill and solid surfaces must be unchanged"
    );
    // Eight of the file's forty internal perimeter moves are on the bed, and
    // those are the only ones left as sliced.
    assert_eq!(
        result.matches("E0.64000").count(),
        8,
        "every wall above the bed must be re-metered:\n{result}"
    );
}

/// A file handed no flags at all still gets the shipped flow.
#[test]
fn the_shipped_default_rescales_the_walls() {
    let sandbox = Sandbox::new("default-flow");
    let path = sandbox.with_gcode(&sample_gcode());
    assert!(run(&[path.to_str().unwrap()]).status.success());

    let result = fs::read_to_string(&path).expect("read result");
    // 0.64 at 1.025, on every internal perimeter move but the bed layer's and
    // those the raise meters for a step of their own: 1.25 while a column
    // climbs, 0.5 where one is capped.
    assert_eq!(
        result.matches("E0.65600").count(),
        20,
        "the walls metered over:\n{result}"
    );
    assert_eq!(result.matches("E0.82000").count(), 8, "climbing");
    assert_eq!(result.matches("E0.32800").count(), 4, "capped");
    assert_eq!(result.matches("E0.64000").count(), 8, "the bed layer");
    assert_eq!(
        result.matches("E0.67616").count(),
        16,
        "the visible wall metered over as well, and shortened by coming in"
    );
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "and only the bed layer's left as sliced"
    );
}

/// The visible wall is brought toward the loop behind it by half of what the
/// multiplier would have added as flow, so the joint against it closes without
/// the part growing. It needs the width the wall was metered at, which only the
/// file can state.
#[test]
fn the_visible_wall_is_drawn_in_where_the_file_states_its_width() {
    let sandbox = Sandbox::new("skin-inset");
    let stated = sample_gcode().replace(
        "; layer_height = 0.2\n",
        "; layer_height = 0.2\n; external_perimeter_extrusion_width = 0.4\n",
    );
    let path = sandbox.with_gcode(&stated);
    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert_wellformed(&result);
    // A 0.4 mm wall is laid 0.357 mm from its neighbour at these layers, so at
    // the flow its geometry asks for, 1.025, it widens by 0.0089 and comes in
    // by half of that on all four sides, landing its outer face back where it
    // was. Four of the file's five layers: the one on the build plate is left
    // exactly as sliced.
    assert_eq!(
        result.matches("G1 X19.996 Y0.004 ").count(),
        4,
        "the visible wall must come in by the offset:\n{result}"
    );
    assert_eq!(
        result.matches("E0.67620").count(),
        16,
        "and carry the filament its new width asks for"
    );
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "only the bed layer's four beads may be left as sliced"
    );
    assert_eq!(
        result.matches("G1 X20.000 Y0.000 E0.66000").count(),
        1,
        "and only on the bed layer"
    );
}

/// A file that states no width still has its visible wall drawn in. Scaling a
/// wall without moving it grows the part by half of what the wall gained, so
/// the offset falls back to the same reference profile the flow does rather
/// than to nothing. Cura writes its settings in a form nothing else parses,
/// which is the file this is about.
#[test]
fn a_file_that_states_no_wall_width_falls_back_to_the_reference_profile() {
    let sandbox = Sandbox::new("skin-untouched");
    let path = sandbox.with_gcode(&sample_gcode());
    assert!(run(&[path.to_str().unwrap()]).status.success());

    let result = fs::read_to_string(&path).expect("read result");
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "only the bed layer's visible wall may be left as sliced:\n{result}"
    );
    // 0.45 mm at 0.2 mm layers and a flow of 1.025 comes in by 0.005.
    assert_eq!(
        result.matches("G1 X19.995 Y0.005 ").count(),
        4,
        "and the rest must come in by the reference profile's offset:\n{result}"
    );
    assert_eq!(
        result.matches("G1 X20.000 Y0.000 E").count(),
        1,
        "leaving only the bed layer where the slicer drew it"
    );
}

#[test]
fn help_and_version_are_available() {
    for command in [["--help"], ["--version"]] {
        let output = run(&command);
        assert!(output.status.success(), "{command:?} failed");
        assert!(!output.stdout.is_empty());
    }
    assert!(run(&["--help"]).status.success());
}

#[test]
fn the_slicer_environment_supplies_the_layer_height() {
    let sandbox = Sandbox::new("env-layer-height");
    // Without the comment the Z steps would measure 0.2, so 0.3 can only have
    // come from the environment.
    let path = sandbox.with_gcode(&sample_gcode().replace("; layer_height = 0.2\n", ""));
    let file = path.to_str().unwrap();

    let output = run_with_env(&["--verbose", file], &[("SLIC3R_LAYER_HEIGHT", "0.3")]);
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("raised by 0.150 mm"), "{report}");
    assert!(!report.contains("warning"), "{report}");
}

/// An adaptive slice has no one layer height, so the nominal a slicer exports
/// describes none of its layers and cannot stand in for measuring them.
#[test]
fn a_varied_layer_height_is_measured_rather_than_taken_from_the_slicer() {
    let sandbox = Sandbox::new("varied-layer-height");
    // Every layer is 0.2 but the fourth, which is 0.1, so a raise of half the
    // exported 0.3 would be one and a half times its own height.
    let planes = [0.2, 0.4, 0.6, 0.7, 0.9];
    let path = sandbox.with_gcode(&gcode_at(&planes));
    let file = path.to_str().unwrap();

    let output = run_with_env(&["--verbose", file], &[("SLIC3R_LAYER_HEIGHT", "0.3")]);
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("varied the layer height"), "{report}");
    assert!(
        report.contains("raised by 0.050 to 0.100 mm"),
        "each layer takes its own half, not half of the exported 0.3: {report}"
    );
}

#[test]
fn slicer_settings_that_defeat_the_transform_are_reported() {
    let sandbox = Sandbox::new("env-warnings");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(
        &[path.to_str().unwrap()],
        &[
            ("SLIC3R_WALL_SEQUENCE", "inner wall/outer wall"),
            ("SLIC3R_WALL_LOOPS", "1"),
            ("SLIC3R_SPIRAL_MODE", "1"),
            ("SLIC3R_ENABLE_ARC_FITTING", "1"),
        ],
    );
    assert!(output.status.success(), "{output:?}");

    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("spiral vase"), "{report}");
    assert!(
        !report.contains("arc fitting"),
        "arc fitting is handled, so it is not a setting that defeats anything: {report}"
    );
    assert!(report.contains("1 wall(s)"), "{report}");
}

/// Two walls leave exactly one internal perimeter per region. That loop is
/// raised against the external perimeter it was inset from, so the run bricks
/// rather than reporting the file as beyond help.
#[test]
fn two_walls_are_bricked_rather_than_refused() {
    let sandbox = Sandbox::new("env-two-walls");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(
        &["--verbose", path.to_str().unwrap()],
        &[("SLIC3R_PERIMETERS", "2")],
    );
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(!report.contains("wall(s)"), "{report}");
    assert!(report.contains("3 raised"), "{report}");
}

/// One wall is the visible one, with nothing hidden behind it to shift, so the
/// run has to say so rather than report having done nothing.
#[test]
fn a_single_wall_is_reported_as_leaving_nothing_to_raise() {
    let sandbox = Sandbox::new("env-one-wall");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(&[path.to_str().unwrap()], &[("SLIC3R_PERIMETERS", "1")]);
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("1 wall(s)"), "{report}");
    assert!(report.contains("two walls or more"), "{report}");
}

/// Arc fitting is a print setting, so the file carries the evidence even when
/// the tool is run by hand rather than by a slicer. `brick` shifts an arc with
/// the loop around it, so it has nothing to say about one.
#[test]
fn walls_emitted_as_arcs_draw_no_warning() {
    let sandbox = Sandbox::new("arcs");
    let arced = sample_gcode().replace(
        "G1 X19.550 Y19.550 E0.64000",
        "G3 X19.550 Y19.550 I1 J1 E0.64000",
    );
    let path = sandbox.with_gcode(&arced);

    let output = run_with_env(
        &[path.to_str().unwrap()],
        &[("SLIC3R_ENABLE_ARC_FITTING", "1")],
    );
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(!report.contains("arc"), "{report}");
}

#[test]
fn a_well_configured_slicer_draws_no_warnings() {
    let sandbox = Sandbox::new("env-quiet");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(
        &[path.to_str().unwrap()],
        &[
            ("SLIC3R_EXTERNAL_PERIMETERS_FIRST", "1"),
            ("SLIC3R_PERIMETERS", "3"),
            ("SLIC3R_SPIRAL_VASE", "0"),
            ("SLIC3R_ARC_FITTING", "emit_center"),
        ],
    );
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(!report.contains("warning"), "{report}");
}

/// The visible wall anchors the alternation by being recognised, not by being
/// counted from one end, so once it is in the contour the order the slicer
/// printed the walls in no longer decides anything. It is still the fallback
/// for a contour that holds no visible wall.
#[test]
fn the_wall_order_no_longer_decides_where_the_alternation_starts() {
    let sandbox = Sandbox::new("wall-order");

    let bricked = |settings: &[(&str, &str)]| {
        let path = sandbox.with_gcode(&sample_gcode());
        let output = run_with_env(&[path.to_str().unwrap()], settings);
        assert!(output.status.success(), "{output:?}");
        let result = fs::read_to_string(&path).expect("read result");
        assert_wellformed(&result);
        result
    };

    assert_eq!(
        bricked(&[("SLIC3R_EXTERNAL_PERIMETERS_FIRST", "1")]),
        bricked(&[("SLIC3R_EXTERNAL_PERIMETERS_FIRST", "0")]),
        "the visible wall anchors the stack whichever end it was printed at"
    );
}

#[test]
fn crlf_input_is_accepted() {
    let sandbox = Sandbox::new("crlf");
    let path = sandbox.with_gcode(&sample_gcode().replace('\n', "\r\n"));
    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert!(!result.contains('\r'));
    assert_wellformed(&result);
}

/// The binary streams a file through the same transform the library runs over a
/// string, so the two have to agree byte for byte. This is what pins the line
/// reader, the buffered writer and the atomic rename to the reference result.
#[test]
fn streaming_a_file_matches_rewriting_it_in_memory() {
    let sandbox = Sandbox::new("streaming-matches");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);

    let in_memory = brick::apply(&source, &brick::Config::default()).gcode;
    let out = sandbox.path().join("brick.gcode");
    let output = run(&["--output", out.to_str().unwrap(), path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let streamed = fs::read_to_string(&out).expect("read result");
    assert_eq!(streamed, in_memory, "brick diverged from the library");
}

/// Nothing this tool writes may ask the nozzle to go below the build plate.
#[test]
fn no_transform_ever_commands_a_z_below_the_bed() {
    let sandbox = Sandbox::new("below-bed");
    let path = sandbox.with_gcode(&sample_gcode());

    for args in [vec!["plain"], vec!["verbose", "--verbose"]] {
        let out = sandbox.path().join(format!("{}.gcode", args[0]));
        let mut call: Vec<&str> = args[1..].to_vec();
        call.extend(["--output", out.to_str().unwrap(), path.to_str().unwrap()]);
        let output = run(&call);
        assert!(output.status.success(), "{args:?}: {output:?}");

        let result = fs::read_to_string(&out).expect("read result");
        assert_wellformed(&result);
        for line in result.lines() {
            let body = line.split(';').next().unwrap_or("");
            for word in body.split_whitespace().skip(1) {
                if let Some(digits) = word.strip_prefix('Z') {
                    let z: f64 = digits.parse().expect("a number");
                    assert!(z >= 0.0, "{args:?} commanded {line}");
                }
            }
        }
    }
}

/// Numbers are written digit by digit rather than through the standard
/// formatter. A coordinate that sits exactly on a rounding boundary is where
/// the two could part, so the whole binary is checked against a file made of
/// them: every value must read back as the one the formatter would print.
#[test]
fn coordinates_on_a_rounding_boundary_survive_the_binary() {
    let sandbox = Sandbox::new("rounding");

    let mut source = String::from("; layer_height = 0.2\nM83\n");
    for layer in 0..4 {
        let z = 0.2 + f64::from(layer) * 0.2;
        source.push_str(";LAYER_CHANGE\n");
        source.push_str(&format!("G1 Z{z:.3} F600\n"));
        source.push_str(";TYPE:Perimeter\n");
        for inset in [0.0_f64, 0.4375] {
            // Odd sixteenths land exactly on a half-way point at three
            // decimals, where rounding goes to even rather than away from zero.
            let (near, far) = (1.0625 + inset, 9.9375 - inset);
            source.push_str(&format!("G1 X{near} Y{near} F9000\n"));
            for (x, y) in [(far, near), (far, far), (near, far), (near, near)] {
                source.push_str(&format!("G1 X{x} Y{y} E0.53125\n"));
            }
        }
    }
    let path = sandbox.with_gcode(&source);

    let out = sandbox.path().join("brick.gcode");
    let output = run(&["--output", out.to_str().unwrap(), path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&out).expect("read result");
    assert_wellformed(&result);
    for line in result.lines() {
        let body = line.split(';').next().unwrap_or("");
        for word in body.split_whitespace().skip(1) {
            let (letter, digits) = word.split_at(1);
            if !matches!(letter, "X" | "Y" | "Z" | "E" | "F") {
                continue;
            }
            let value: f64 = digits.parse().expect("a number");
            let decimals = digits.split_once('.').map_or(0, |(_, tail)| tail.len());
            assert_eq!(
                digits,
                format!("{value:.decimals$}"),
                "wrote {word} in: {line}"
            );
        }
    }
}
