#!/usr/bin/env python3
"""Check `beads.py` against `src/brick.rs`, so a diagram cannot drift from it.

Two kinds of check, because either alone lets a change through:

1. **Constants.** Every number `beads.py` holds is read back out of the Rust
   and compared. A constant renamed or retuned on one side fails here.
2. **Output.** A synthetic slice is put through the real compiled binary and
   the coordinates it emits are compared with the ones `beads.py` predicts.
   This is what catches a formula that is right in isolation and wrong in
   place.

    python3 pin.py            # builds the binary if needed
    python3 pin.py --binary target/release/bricklayers

Exit status is 0 when the model and the binary agree.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import beads

ROOT = Path(__file__).resolve().parents[4]
BRICK = ROOT / "src" / "brick.rs"

TOLERANCE = 5e-4
"""Half a micron either way: a coordinate is written to three decimals."""


def rust_constant(source: str, name: str) -> float:
    found = re.search(rf"const {name}: f64 = ([-0-9.eE]+);", source)
    if not found:
        raise SystemExit(f"{name} is gone from src/brick.rs")
    return float(found.group(1))


def rust_usize(source: str, name: str) -> int:
    found = re.search(rf"const {name}: usize = ([0-9]+);", source)
    if not found:
        raise SystemExit(f"{name} is gone from src/brick.rs")
    return int(found.group(1))


def check_constants(source: str) -> list[str]:
    wrong = []
    pairs = [
        ("DEFAULT_EXTRA_FLOW", beads.DEFAULT_EXTRA_FLOW),
        ("MIN_EXTRA_FLOW", beads.MIN_EXTRA_FLOW),
        ("MAX_EXTRA_FLOW", beads.MAX_EXTRA_FLOW),
        ("REFERENCE_NOZZLE", beads.REFERENCE_NOZZLE),
        ("REFERENCE_HEIGHT", beads.REFERENCE_HEIGHT),
        ("REFERENCE_WIDTH", beads.REFERENCE_WIDTH),
    ]
    for name, mine in pairs:
        theirs = rust_constant(source, name)
        if theirs != mine:
            wrong.append(f"{name}: brick.rs says {theirs}, beads.py says {mine}")
    ramp = rust_usize(source, "RAMP")
    if ramp != beads.RAMP:
        wrong.append(f"RAMP: brick.rs says {ramp}, beads.py says {beads.RAMP}")
    if "MAX_WALL_FLOW" in source:
        wrong.append("MAX_WALL_FLOW is back in brick.rs; the ceiling is derived")
    return wrong


HEIGHT = 0.2
WIDTH = 0.45
SKIN = 0.4
SIDE = 20.0
PLANES = [0.2, 0.4, 0.6, 0.8, 1.0]


def synthetic() -> str:
    """A PrusaSlicer-shaped slice, the same shape `tests/end_to_end.rs` uses.

    Walls alone are not enough: with nothing printed over them the survey finds
    no cell covering a loop and caps every column, which measures the wrong
    thing. The widths are stated so the flow is derived rather than guessed.
    """
    text = [
        "; generated by PrusaSlicer",
        "M83 ; extruder relative mode",
        f"; layer_height = {HEIGHT}",
        f"; perimeter_extrusion_width = {WIDTH}",
        f"; external_perimeter_extrusion_width = {SKIN}",
    ]
    for at, z in enumerate(PLANES):
        text.append(";LAYER_CHANGE")
        text.append(f"G1 Z{z:.3f} F9000")
        text.append(";TYPE:External perimeter")
        text.append("G1 X0 Y0 F9000")
        for x, y in [(SIDE, 0.0), (SIDE, SIDE), (0.0, SIDE), (0.0, 0.0)]:
            text.append(f"G1 X{x:.3f} Y{y:.3f} E0.66000 ; skin")
        text.append(";TYPE:Perimeter")
        for inset in (0.45, 0.90):
            text.append(f"G1 X{inset:.3f} Y{inset:.3f} F9000")
            far = SIDE - inset
            for x, y in [(far, inset), (far, far), (inset, far), (inset, inset)]:
                text.append(f"G1 X{x:.3f} Y{y:.3f} E0.64000")
        solid = at == 0 or at + 1 == len(PLANES)
        text.append(";TYPE:Solid infill" if solid else ";TYPE:Internal infill")
        text.append("G1 X2 Y2 F9000")
        text.append("G1 X18 Y18 E1.20000")
    text.append("M104 S0")
    return "\n".join(text) + "\n"


def build(binary: Path | None) -> Path:
    if binary:
        return binary
    # Always, not only when the file is missing: a stale release build is
    # exactly the drift this script exists to catch, and it would report the
    # Rust as wrong.
    subprocess.run(
        ["cargo", "build", "--release"], cwd=ROOT, check=True, capture_output=True
    )
    return ROOT / "target" / "release" / "bricklayers"


def check_output(binary: Path, extra: float) -> list[str]:
    """Run the binary over the synthetic slice and compare what it emits."""
    wrong = []
    with tempfile.TemporaryDirectory() as room:
        source = Path(room) / "pin.gcode"
        source.write_text(synthetic(), encoding="utf-8")
        result = subprocess.run(
            [str(binary), "--extra-flow", f"{extra * 100:g}", str(source)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            return [f"the binary refused the fixture: {result.stderr.strip()}"]
        produced = source.read_text(encoding="utf-8")

    flow = beads.automatic_flow(HEIGHT, WIDTH, extra)
    inward = beads.skin_offset(flow, SKIN, HEIGHT)
    predicted = f"G1 X{SIDE - inward:.3f} Y{inward:.3f} "
    if predicted not in produced:
        found = [line for line in produced.splitlines() if line.endswith("; skin")]
        wrong.append(
            f"the visible wall should be drawn in to {predicted.strip()!r}, got "
            f"{found[len(found) // 2] if found else 'no visible wall at all'!r}"
        )

    # The layer on the plate is never raised and the top one is capped, so the
    # columns that stand are the ones between them.
    raises = [
        float(found)
        for found in re.findall(r"Z([0-9.]+) ; bricklayers brick raised", produced)
    ]
    expected = [PLANES[at] + beads.rise(at, HEIGHT) for at in range(1, len(PLANES) - 1)]
    if len(raises) != len(expected):
        wrong.append(f"expected {len(expected)} raised columns, got {len(raises)}")
    for at, (got, want) in enumerate(zip(raises, expected), start=1):
        if abs(got - want) > TOLERANCE:
            wrong.append(f"raise {at}: binary put it at {got}, the model says {want}")
    return wrong


def main() -> int:
    parse = argparse.ArgumentParser(description=__doc__)
    parse.add_argument("--binary", type=Path, default=None)
    parse.add_argument("--extra-flow", type=float, default=beads.MAX_EXTRA_FLOW)
    args = parse.parse_args()

    source = BRICK.read_text(encoding="utf-8")
    wrong = check_constants(source)
    wrong += check_output(build(args.binary), args.extra_flow)

    for line in wrong:
        print(f"drift: {line}", file=sys.stderr)
    if wrong:
        return 1
    print(f"beads.py agrees with {BRICK.relative_to(ROOT)} and the binary")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
